auto: true
pygments: true
server_port: 4001
title : tamamaxox-test
author: 
  name: tamamaxox

F:
  path:
    css: /assets/stylesheets
    scripts: /assets/scripts
  nav_total: 4

production_url : http://tamamaxox.github.com

