auto: true
pygments: true
permalink: /:categories/:title
server_port: 4001
title : hm&deartree
author: 
  name: tamamaxox

F:
  path:
    css: /assets/stylesheets
    scripts: /assets/scripts

production_url : http://tamamaxox.github.com
gatekeeper_url: http://tamamaxoxkeeper.herokuapp.com

oauth_client_id: 5082addd8484a7b0066b

baseurl: "backend/"
