auto: true
pygments: true
server_port: 4001
title : hm&deartree
author: 
  name: tamamaxox

F:
  path:
    css: /assets/stylesheets
    scripts: /assets/scripts
  nav_total: 10

production_url : http://tamamaxox.github.com

