auto: true
pygments: true
server_port: 4001
title : tamamaxox-test
author: 
  name: tamamaxox

F:
  path:
    css: /assets/stylesheets
    libs: /assets/libs
    script: /assets/javascript
  nav_total: 4

production_url : http://tamamaxox.github.com

