// Generated by CoffeeScript 1.3.3
(function() {
  var config, cssc, fs, less, lessToCss, parser, requirejs;

  requirejs = require('./r.js');

  fs = require('fs');

  less = require('./less');

  config = {
    baseUrl: "./libs",
    paths: {
      jquery: "empty:"
    },
    name: "F",
    exclude: ["bootstrap-scrollspy"],
    out: "../assets/scripts/o.js"
  };

  cssc = {
    input: "./libs/o.less",
    paths: ['./libs', './libs/F_less'],
    output: "../assets/stylesheets/o.css"
  };

  parser = new less.Parser({
    paths: cssc.paths
  });

  lessToCss = function() {
    return fs.readFile(cssc.input, 'utf-8', function(e, data) {
      if (e) {
        return console.log("err:" + e);
      } else {
        return parser.parse(data, function(e, tree) {
          var css, fd;
          if (e) {
            return console.log("err:" + e);
          } else {
            css = tree.toCSS({
              compress: true
            });
            fd = fs.openSync(cssc.output, 'w');
            return fs.writeSync(fd, css, 0, "utf-8");
          }
        });
      }
    });
  };

  requirejs.optimize(config);

  lessToCss();

  fs.watch("./libs/", function(event, filename) {
    console.log("event is: " + event);
    if (filename) {
      console.log("filename provided: " + filename);
      if (/\.js$/.test(filename)) {
        console.log(".js");
        requirejs.optimize(config);
      }
      if (/\.less$/.test(filename)) {
        console.log(".less");
        return lessToCss();
      }
    } else {
      return console.log('filename not provided');
    }
  });

}).call(this);
